### ISSUE TITLE
GriefPrevention support 

### ISSUE THREAD

**Issue by JesusLion** [redstone/FreshWilderness#5]
would be great!

**Comment by MarkehMe** [comment]
Great idea :) will be in the next release

**Comment by Bysokar** [comment]
@markehme Just grab the code from regenerator and tweak it for use with your plugin :)

Ps is this working finally? :D

**Comment by Bysokar** [comment]
Scratch that ill add the support and offer it to You As a Pr. Good work on this plugin dude!

**Comment by MarkehMe** [comment]
@Bysokar that would be awesome, thanks :)

**Comment by ArtNRG** [comment]
@MarkehMe the issue is already opened, will be glad to see this support.

**Comment by Bysokar** [comment]
Haha Regenerator not for you hey bud

**Comment by MarkehMe** [comment]
✅ GriefPrevention support added
