### ISSUE TITLE
Residence Support

### ISSUE THREAD

**Issue by chillerkraft** [redstone/FreshWilderness#7]
http://ltcraft.lt/Residence/
https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-11.11480/
the link to the free versions is on there spigot page

**Comment by MarkehMe** [comment]
Sure :)

**Comment by chillerkraft** [comment]
![image](https://cloud.githubusercontent.com/assets/10078199/25759714/9ef9d29c-31a1-11e7-9d1c-ab9cf1a450ae.png)

**Comment by chillerkraft** [comment]
how's it going?

**Comment by MarkehMe** [comment]
✅ Added support for Residence
