### ISSUE TITLE
Worldguard regions, with ProtectionStones; MultiWorld support

### ISSUE THREAD

**Issue by download042** [redstone/FreshWilderness#8]
Hello!

I would like to ask you the following:
How can i add in the config regions maded by the ProtectionStones plugin?
(https://www.spigotmc.org/resources/protectionstones.10096/)
In my server, the players protecting many WorldGuard area with this plugin.

Does the plugin handle more worlds? I just want to modify one World with your plugin.

sry for bad English :p
Thank you in advance for your answer!

**Comment by MarkehMe** [comment]
Hi! 

Wilderness for WorldGuard is done automatically. __global__ is considered the wilderness. 

However, we can not track when the region is removed (and therefore, log it for refresh) as WorldGuard does not notify other plugins when a region is removed.

It is tracked again when a player makes a change after breaking/placing blocks in those chunks. 

Does this make sense? :)

**Comment by download042** [comment]
And what about the multiworld separation?
Thank you for the fast answer.

**Comment by MarkehMe** [comment]
There is a permission `freshwilderness.ignore` that you can apply to players to not break blocks in a world.

Do you use a permissions plugin? You can use that to disable it in a world.

**Comment by download042** [comment]
Of course, I use PermissionsEX, but with global settings.

Whit this permission the players not allowed to breaking blocks? I understand it correctly?

I have a spawn world, nether, end, plotworld, and wild.
In every world breaking the players blocks, in PrisonMines.

**Comment by download042** [comment]
My server is crashing with this plugin. :S

**Comment by MarkehMe** [comment]
> Whit this permission the players not allowed to breaking blocks? I understand it correctly?
No no.. it just doesn't initiate FreshWilderness in that world.

---

Closing this:
- WorldGuard already supported
- ProtectionStones support added
- Multiworld support already done through permissions
